"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";

type Instructor = { email: string; username: string | null; display_name: string; created_at: string; grade: string; contract_status: string; settlement_rate: number; specialty: string; manager_name: string; task_count: number; done_count: number };
type Resource = { id: string; target_email: string; target_name: string; title: string; resource_type: string; request_note: string; delivery_type: "text" | "link" | "file"; placement: "roadmap" | "library" | "contract"; stage: number | null; external_url: string | null; file_name: string | null; size_bytes: number | null; created_at: string };
type ResourceMessage = { id: string; resource_id: string; user_email: string; author_role: "instructor" | "admin"; body: string; created_at: string };
type Task = { id: string; user_email: string; stage: number; title: string; category: string; status: string };
type ProgressUpdate = { id: string; user_email: string; task_id: string; instructor_name: string; stage: number; task_title: string; progress_note: string; question: string; admin_reply: string | null; created_at: string };
type Plan = { user_email: string; display_name: string; content: string; status: string; version: number; reviewer_comment: string | null; review_checklist: string; updated_at: string };
type Issue = { id: string; user_email: string; instructor_name: string; severity: number; category: string; course_name: string; detail: string; immediate_action: string; status: string; admin_action: string | null; admin_reply: string | null; created_at: string };
type CourseRun = { id: string; user_email: string; instructor_name: string; course_title: string; free_lecture_date: string; curriculum_date: string };
type SupportRequest = { id: string; user_email: string; instructor_name: string; request_type: string; message: string; admin_reply: string | null; status: string; created_at: string };
type AdminData = { user: { email: string; displayName: string; role: string }; instructors: Instructor[]; resources: Resource[]; resourceMessages: ResourceMessage[]; tasks: Task[]; progressUpdates: ProgressUpdate[]; plans: Plan[]; issues: Issue[]; courseRuns: CourseRun[]; supportRequests: SupportRequest[] };

const emptyInstructor = { displayName: "", email: "", username: "", password: "", specialty: "", grade: "연습강사", settlementRate: "50" };
const emptyResource = { targetEmail: "", title: "", resourceType: "강의자료", requestNote: "", deliveryType: "text" as "text" | "link" | "file", placement: "roadmap" as "roadmap" | "library" | "contract", stage: "1", externalUrl: "" };
const reviewChecks = [{ key: "goal", label: "행동 중심 목표" }, { key: "practice", label: "실습 산출물" }, { key: "disclaimer", label: "개인차 명시" }, { key: "copyright", label: "저작권 확인" }];
const planLabels: Record<string, string> = { courseTitle: "강의명", audience: "대상 수강생", format: "강의 형태", currentSituation: "현재 상황", painPoint: "핵심 불편", expectedChange: "기대 변화", goals: "행동 목표", deliverable: "결과물", curriculum: "커리큘럼", practice: "직접 실습", freeFlow: "무료강의 흐름", valueBoundary: "무료·본강의 구분", zoomPlan: "Zoom 운영", notice: "사전·사후 안내", coachRoom: "코치방 운영", feedback: "진행 공유·피드백", evidence: "성과 근거", riskCheck: "위험 표현 점검" };
function formatDate(value: string) { return new Intl.DateTimeFormat("ko-KR", { year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(value)); }
function formatBytes(value: number | null) { if (!value) return "파일"; return value < 1024 * 1024 ? `${Math.max(1, Math.round(value / 1024))}KB` : `${(value / 1024 / 1024).toFixed(1)}MB`; }
function parseObject(value: string | null | undefined) { try { return JSON.parse(value ?? "{}") as Record<string, string | boolean>; } catch { return {}; } }

export function AdminPortal({ initialUser }: { initialUser: { displayName: string; email: string } }) {
  const [data, setData] = useState<AdminData | null>(null);
  const [tab, setTab] = useState<"instructors" | "resources" | "monitoring">("instructors");
  const [selectedEmail, setSelectedEmail] = useState("");
  const [instructor, setInstructor] = useState(emptyInstructor);
  const [resource, setResource] = useState(emptyResource);
  const [file, setFile] = useState<File | null>(null);
  const [credentials, setCredentials] = useState({ username: "uhbee", password: "" });
  const [needsLogin, setNeedsLogin] = useState(false);
  const [busy, setBusy] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const [replyDrafts, setReplyDrafts] = useState<Record<string, string>>({});
  const [issueDrafts, setIssueDrafts] = useState<Record<string, { action: string; reply: string }>>({});
  const [planComment, setPlanComment] = useState(""); const [planStatus, setPlanStatus] = useState("revision"); const [planChecklist, setPlanChecklist] = useState<Record<string, boolean>>({});
  const instructorHref = "/";

  const load = async () => { setBusy("load"); setError(""); try { const response = await fetch("/api/admin", { cache: "no-store" }); const payload = await response.json() as AdminData & { error?: string }; if (response.status === 403) { setData(null); setNeedsLogin(true); return; } if (!response.ok) throw new Error(payload.error ?? "관리자 데이터를 불러오지 못했습니다."); setData(payload); setNeedsLogin(false); setSelectedEmail((current) => current && payload.instructors.some((i) => i.email === current) ? current : payload.instructors.at(0)?.email ?? ""); } catch (e) { setError(e instanceof Error ? e.message : "관리자 데이터를 불러오지 못했습니다."); } finally { setBusy(""); } };
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (!message) return; const timer = window.setTimeout(() => setMessage(""), 3200); return () => window.clearTimeout(timer); }, [message]);
  const selectedInstructor = data?.instructors.find((i) => i.email === selectedEmail);
  const selectedPlan = data?.plans.find((p) => p.user_email === selectedEmail);
  useEffect(() => { setPlanComment(selectedPlan?.reviewer_comment ?? ""); setPlanStatus(selectedPlan?.status === "approved" ? "approved" : "revision"); const parsed = parseObject(selectedPlan?.review_checklist); setPlanChecklist(Object.fromEntries(Object.entries(parsed).map(([k, v]) => [k, Boolean(v)]))); }, [selectedEmail, selectedPlan?.version]);
  const completedAverage = useMemo(() => { if (!data?.instructors.length) return 0; return Math.round(data.instructors.reduce((sum, i) => sum + Number(i.done_count) / Math.max(Number(i.task_count), 1) * 100, 0) / data.instructors.length); }, [data]);
  const postJson = async (payload: Record<string, unknown>, success: string) => { setBusy(String(payload.action)); setError(""); try { const response = await fetch("/api/admin", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error ?? "요청을 처리하지 못했습니다."); setMessage(success); await load(); } catch (e) { setError(e instanceof Error ? e.message : "요청을 처리하지 못했습니다."); setBusy(""); } };

  const login = async (event: FormEvent) => { event.preventDefault(); setBusy("login"); setError(""); try { const response = await fetch("/api/admin/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(credentials) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error ?? "관리자 로그인에 실패했습니다."); setCredentials((c) => ({ ...c, password: "" })); setNeedsLogin(false); setMessage("관리자 계정으로 로그인했습니다."); await load(); } catch (e) { setError(e instanceof Error ? e.message : "관리자 로그인에 실패했습니다."); setBusy(""); } };
  const logout = async () => { await fetch("/api/admin/login", { method: "DELETE" }); setData(null); setNeedsLogin(true); setMessage("로그아웃했습니다."); };
  const registerInstructor = async (event: FormEvent) => { event.preventDefault(); await postJson({ action: "registerInstructor", ...instructor, settlementRate: Number(instructor.settlementRate) }, "신규 강사를 등록했습니다."); setInstructor(emptyInstructor); };
  const createResource = async (event: FormEvent) => { event.preventDefault(); setBusy("resource"); setError(""); try { const form = new FormData(); form.set("action", "createResource"); Object.entries(resource).forEach(([k, v]) => form.set(k, v)); if (file) form.set("file", file); const response = await fetch("/api/admin", { method: "POST", body: form }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error ?? "자료를 전달하지 못했습니다."); setResource(emptyResource); setFile(null); const input = document.getElementById("resource-file") as HTMLInputElement | null; if (input) input.value = ""; setMessage("선택한 강사에게 자료를 전달했습니다."); await load(); } catch (e) { setError(e instanceof Error ? e.message : "자료를 전달하지 못했습니다."); setBusy(""); } };
  const deleteResourceMessage = async (id: string) => { if (!window.confirm("선택한 답변을 삭제할까요? 삭제한 내용은 복구할 수 없습니다.")) return; await postJson({ action: "deleteResourceMessage", id }, "선택한 답변을 삭제했습니다."); };

  if (needsLogin && !data) return <main className="admin-access-shell"><section className="admin-access-card admin-login-card"><a className="admin-login-brand" href={instructorHref}>UhB <span>ADMIN CONSOLE</span></a><span>ADMIN SIGN IN</span><h1>관리자 계정으로<br />로그인하세요.</h1><p>강사 등록, 강사용 자료 전달, 답변과 검토는 로그인 후 이용할 수 있습니다.</p><form onSubmit={login}><label><span>관리자 계정</span><input autoComplete="username" required value={credentials.username} onChange={(e) => setCredentials({ ...credentials, username: e.target.value })} /></label><label><span>비밀번호</span><input type="password" autoComplete="current-password" required value={credentials.password} onChange={(e) => setCredentials({ ...credentials, password: e.target.value })} /></label>{error && <div className="admin-login-error">{error}</div>}<button className="primary-button full" disabled={busy === "login"}>{busy === "login" ? "확인하는 중…" : "관리자 로그인"}</button></form><a className="admin-login-back" href={instructorHref}>← 강사 센터로 돌아가기</a></section></main>;
  if (error && !data) return <main className="admin-access-shell"><section className="admin-access-card"><h1>관리자 페이지에 접근할 수 없습니다.</h1><p>{error}</p><button className="primary-button" onClick={() => void load()}>다시 확인</button></section></main>;

  const instructorOptions = <><option value="">{data?.instructors.length ? "강사를 선택하세요" : "등록된 강사가 없습니다"}</option>{data?.instructors.map((i) => <option key={i.email} value={i.email}>{i.display_name} · {i.email}</option>)}</>;
  const selectedTasks = data?.tasks.filter((t) => t.user_email === selectedEmail) ?? [];
  const selectedResources = data?.resources.filter((resource) => resource.target_email === selectedEmail && resource.placement === "roadmap" && resource.delivery_type !== "file") ?? [];
  const selectedResourceMessages = data?.resourceMessages.filter((item) => item.user_email === selectedEmail) ?? [];
  const selectedIssues = data?.issues.filter((x) => x.user_email === selectedEmail) ?? [];
  const selectedSupports = data?.supportRequests.filter((x) => x.user_email === selectedEmail) ?? [];
  const selectedRuns = data?.courseRuns.filter((x) => x.user_email === selectedEmail) ?? [];
  const planContent = parseObject(selectedPlan?.content);

  return <div className="admin-portal-shell"><aside className="admin-portal-sidebar"><a className="admin-wordmark" href={instructorHref}><strong>UhB</strong><span>ADMIN<br />CONSOLE</span></a><div className="admin-identity"><span>관</span><div><strong>UhB 관리자</strong><small>관리자</small></div></div><nav aria-label="관리자 메뉴"><button className={tab === "instructors" ? "active" : ""} onClick={() => setTab("instructors")}><span>01</span>강사 관리</button><button className={tab === "resources" ? "active" : ""} onClick={() => setTab("resources")}><span>02</span>강사용 자료 전달</button><button className={tab === "monitoring" ? "active" : ""} onClick={() => setTab("monitoring")}><span>03</span>강사별 진행 관리</button></nav><div className="admin-sidebar-actions"><button onClick={() => void logout()}>관리자 로그아웃</button><a className="admin-back-link" href={instructorHref}>← 강사 센터로 돌아가기</a></div></aside>
    <section className="admin-portal-content"><header className="admin-portal-topbar"><div><span>OPERATIONS</span><strong>{tab === "instructors" ? "강사 관리" : tab === "resources" ? "강사용 자료 전달" : "강사별 진행 관리"}</strong></div><div><i className={busy === "load" ? "loading" : ""} />{busy === "load" ? "데이터 확인 중" : "운영 데이터 연결됨"}</div></header><main className="admin-portal-stage"><div className="admin-page-heading"><div><span>INSTRUCTOR OPERATIONS</span><h1>강사별 자료와 진행을<br />정확하게 관리하세요.</h1><p>등록 강사마다 단계 자료, 안내 답변, 기획안, 위기 이슈와 문의를 분리해 관리합니다.</p></div><button className="secondary-button" onClick={() => void load()}>새로고침</button></div><section className="admin-metric-grid"><article><span>등록 강사</span><strong>{data?.instructors.length ?? 0}</strong><small>명</small></article><article><span>평균 온보딩</span><strong>{completedAverage}</strong><small>%</small></article><article><span>전달 자료</span><strong>{data?.resources.length ?? 0}</strong><small>건</small></article><article className="dark"><span>미답변 문의</span><strong>{data?.supportRequests.filter((x) => x.status === "open").length ?? 0}</strong><small>건</small></article></section>

      {tab === "instructors" && <div className="admin-work-grid">
        <form className="admin-form-panel" onSubmit={registerInstructor}>
          <div className="admin-panel-title"><span>NEW INSTRUCTOR</span><h2>신규 강사 등록</h2><p>강사가 사용할 아이디와 비밀번호를 직접 정하면 전용 업무 공간과 7단계 로드맵이 함께 생성됩니다. 기존 강사의 ID가 미설정이면 같은 이메일로 계정을 발급할 수 있습니다.</p></div>
          <div className="admin-form-grid two"><label><span>강사명 *</span><input required value={instructor.displayName} onChange={(e) => setInstructor({ ...instructor, displayName: e.target.value })} placeholder="홍길동" /></label><label><span>이메일 *</span><input required type="email" value={instructor.email} onChange={(e) => setInstructor({ ...instructor, email: e.target.value })} placeholder="instructor@example.com" /></label></div>
          <div className="admin-form-grid two"><label><span>로그인 아이디 *</span><input required minLength={4} maxLength={30} pattern="[a-z0-9._-]+" autoComplete="off" value={instructor.username} onChange={(e) => setInstructor({ ...instructor, username: e.target.value.toLowerCase() })} placeholder="honggildong" /><small>영문 소문자·숫자·점·밑줄·하이픈, 4~30자</small></label><label><span>초기 비밀번호 *</span><input required type="password" minLength={8} maxLength={64} autoComplete="new-password" value={instructor.password} onChange={(e) => setInstructor({ ...instructor, password: e.target.value })} placeholder="8자 이상 입력" /><small>강사에게 안전하게 전달해 주세요.</small></label></div>
          <div className="admin-form-grid two"><label><span>전문 분야</span><input value={instructor.specialty} onChange={(e) => setInstructor({ ...instructor, specialty: e.target.value })} placeholder="AI 업무자동화" /></label><label><span>강사 등급</span><select value={instructor.grade} onChange={(e) => setInstructor({ ...instructor, grade: e.target.value })}><option>연습강사</option><option>파트너강사</option><option>전문강사</option><option>마스터강사</option></select></label></div>
          <label><span>정산율 (%)</span><input type="number" min="0" max="100" value={instructor.settlementRate} onChange={(e) => setInstructor({ ...instructor, settlementRate: e.target.value })} /></label><button className="primary-button full" disabled={busy === "registerInstructor"}>{busy === "registerInstructor" ? "등록하는 중…" : "계정과 강사 공간 생성하기"}</button>
        </form>
        <section className="admin-list-panel"><div className="admin-panel-title compact"><span>INSTRUCTOR LIST</span><h2>등록 강사</h2><p>강사를 선택하면 진행 관리 화면으로 이동합니다.</p></div><div className="admin-instructor-list">{data?.instructors.map((i) => { const progress = Math.round(Number(i.done_count) / Math.max(Number(i.task_count), 1) * 100); return <button className="admin-instructor-card" key={i.email} onClick={() => { setSelectedEmail(i.email); setTab("monitoring"); }}><div className="admin-avatar">{i.display_name.slice(0, 1)}</div><div><strong>{i.display_name}<em>{i.grade}</em></strong><span>{i.specialty} · ID {i.username ?? "미설정"} · {i.email}</span><div className="admin-progress"><i><b style={{ width: `${progress}%` }} /></i><small>{progress}%</small></div></div><time>{formatDate(i.created_at)}</time></button>; })}{!data?.instructors.length && <div className="admin-empty"><strong>아직 등록된 강사가 없습니다.</strong><span>왼쪽 양식에서 첫 강사를 등록해 주세요.</span></div>}</div></section>
      </div>}

      {tab === "resources" && <div className="admin-work-grid">
        <form className="admin-form-panel" onSubmit={createResource}><div className="admin-panel-title"><span>INSTRUCTOR DELIVERY</span><h2>강사용 자료 전달</h2><p>단계별 확인 내용·링크·파일과 체결 계약서를 강사별로 전달합니다.</p></div>
          <label><span>대상 강사 *</span><select required disabled={!data?.instructors.length} value={resource.targetEmail} onChange={(event) => setResource({ ...resource, targetEmail: event.target.value })}>{instructorOptions}</select></label>
          <div className="admin-form-grid two"><label><span>전달 위치 *</span><select value={resource.placement} onChange={(event) => { const placement = event.target.value as "roadmap" | "library" | "contract"; setResource({ ...resource, placement, deliveryType: placement === "contract" ? "file" : resource.deliveryType, title: placement === "contract" && !resource.title ? "체결 계약서" : resource.title }); }}><option value="roadmap">강사 육성 로드맵</option><option value="library">자료실</option><option value="contract">계약서 등록</option></select></label>{resource.placement === "roadmap" ? <label><span>로드맵 단계 *</span><select value={resource.stage} onChange={(event) => setResource({ ...resource, stage: event.target.value })}>{Array.from({ length: 7 }, (_, index) => <option value={index + 1} key={index}>0{index + 1}단계</option>)}</select></label> : resource.placement === "library" ? <label><span>자료 카테고리</span><select value={resource.resourceType} onChange={(event) => setResource({ ...resource, resourceType: event.target.value })}><option>기획안</option><option>운영</option><option>Zoom</option><option>코치방</option><option>위기대응</option><option>기타</option></select></label> : <div className="contract-upload-note"><strong>01단계 계약서</strong><span>강사의 ‘계약서 확인하기’에 표시됩니다.</span></div>}</div>
          <label><span>제목 *</span><input required value={resource.title} onChange={(event) => setResource({ ...resource, title: event.target.value })} placeholder="강사가 확인할 항목 또는 자료명" /></label><label><span>확인 내용·전달 메모</span><textarea rows={4} value={resource.requestNote} onChange={(event) => setResource({ ...resource, requestNote: event.target.value })} placeholder="강사가 무엇을 확인하거나 수행해야 하는지 정확히 적어 주세요." /></label>
          {resource.placement !== "contract" && <div className="delivery-switch"><button type="button" className={resource.deliveryType === "text" ? "active" : ""} onClick={() => setResource({ ...resource, deliveryType: "text" })}>내용만 전달</button><button type="button" className={resource.deliveryType === "link" ? "active" : ""} onClick={() => setResource({ ...resource, deliveryType: "link" })}>링크 전달</button><button type="button" className={resource.deliveryType === "file" ? "active" : ""} onClick={() => setResource({ ...resource, deliveryType: "file" })}>파일 업로드</button></div>}
          {resource.deliveryType === "link" && <label><span>자료 링크 *</span><input required type="url" value={resource.externalUrl} onChange={(event) => setResource({ ...resource, externalUrl: event.target.value })} placeholder="https://…" /></label>}{resource.deliveryType === "file" && <label className="admin-file-field"><span>{resource.placement === "contract" ? "체결 계약서 파일" : "업로드 파일"} * <small>최대 25MB</small></span><input id="resource-file" required type="file" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><em>{file ? `${file.name} · ${formatBytes(file.size)}` : "파일을 선택하세요."}</em></label>}<button className="primary-button full" disabled={busy === "resource" || !data?.instructors.length}>{resource.placement === "contract" ? "선택한 강사 계약서 등록하기" : "선택한 강사에게 전달하기"}</button>
        </form>
        <section className="admin-list-panel"><div className="admin-panel-title compact"><span>DELIVERY HISTORY</span><h2>강사별 전달 내역</h2><p>{resource.targetEmail ? "선택한 강사의 내역입니다." : "전체 강사의 내역입니다."}</p></div><div className="admin-resource-list">{data?.resources.filter((item) => !resource.targetEmail || item.target_email === resource.targetEmail).map((item) => <article key={item.id}><span className={`resource-kind ${item.delivery_type}`}>{item.delivery_type === "file" ? "FILE" : item.delivery_type === "link" ? "LINK" : "TEXT"}</span><div><strong>{item.title}</strong><span>{item.target_name} · {item.placement === "roadmap" ? `${item.stage}단계` : item.placement === "contract" ? "계약서" : item.resource_type}</span><small>{item.request_note || item.file_name || item.external_url}</small></div>{item.delivery_type !== "text" && <a href={`/api/resources/${item.id}`} target="_blank">열기 ↗</a>}</article>)}</div></section>
      </div>}

      {tab === "monitoring" && <div className="admin-monitoring"><section className="admin-focus-bar"><div><span>SELECT INSTRUCTOR</span><h2>강사별 진행 관리</h2></div><select value={selectedEmail} onChange={(e) => setSelectedEmail(e.target.value)}>{instructorOptions}</select>{selectedInstructor && <div className="focus-person"><span>{selectedInstructor.display_name.slice(0, 1)}</span><div><strong>{selectedInstructor.display_name}</strong><small>{selectedInstructor.specialty} · {selectedInstructor.email}</small></div></div>}</section>{selectedInstructor ? <>
        <section className="admin-detail-section"><div className="admin-section-heading"><span>01 · ROADMAP</span><h2>로드맵 안내와 답변</h2></div><div className="admin-task-strip">{selectedTasks.map((task) => <article key={task.id}><span>0{task.stage}</span><strong>{task.category}</strong><small>{task.status === "done" ? "완료" : task.status === "review" ? "확인 필요" : task.status === "revision" ? "보완 필요" : "진행 중"}</small></article>)}</div><div className="admin-resource-conversations">{selectedResources.map((resource) => { const draftKey = `resource:${resource.id}`; const messages = selectedResourceMessages.filter((item) => item.resource_id === resource.id); return <article key={resource.id}><header><div><span>0{resource.stage}단계 · {resource.delivery_type === "link" ? "링크 안내" : "확인 안내"}</span><h3>{resource.title}</h3></div><time>{formatDate(resource.created_at)}</time></header><p>{resource.request_note}</p>{resource.delivery_type === "link" && <a href={`/api/resources/${resource.id}`} target="_blank">전달 링크 열기 ↗</a>}<div className="admin-message-thread">{messages.map((item) => <div className={item.author_role} key={item.id}><div><strong>{item.author_role === "admin" ? "관리자" : "강사"}</strong><time>{formatDate(item.created_at)}</time><button onClick={() => void deleteResourceMessage(item.id)}>삭제</button></div><p>{item.body}</p></div>)}{!messages.length && <span className="admin-no-message">아직 등록된 답변이 없습니다.</span>}</div><div className="admin-reply-box"><textarea rows={3} value={replyDrafts[draftKey] ?? ""} onChange={(event) => setReplyDrafts({ ...replyDrafts, [draftKey]: event.target.value })} placeholder="강사에게 보낼 답변을 입력하세요." /><button className="primary-button" onClick={() => void postJson({ action: "replyResource", resourceId: resource.id, reply: replyDrafts[draftKey] }, "강사에게 답변을 전달했습니다.")}>답변 등록</button></div></article>; })}{!selectedResources.length && <div className="admin-empty">이 강사에게 전달한 단계별 확인 내용이나 링크가 없습니다.</div>}</div></section>
        <section className="admin-detail-section"><div className="admin-section-heading"><span>02 · LESSON PLAN</span><h2>강의 기획안 검토</h2></div>{selectedPlan ? <div className="admin-plan-review"><div className="admin-plan-content">{Object.entries(planContent).filter(([, v]) => v).map(([k, v]) => <article key={k}><span>{planLabels[k] ?? k}</span><p>{String(v)}</p></article>)}{!Object.values(planContent).some(Boolean) && <div className="admin-empty">아직 입력된 기획안 내용이 없습니다.</div>}</div><aside><h3>검토 체크리스트</h3>{reviewChecks.map((item) => <label className="admin-check-row" key={item.key}><input type="checkbox" checked={Boolean(planChecklist[item.key])} onChange={(e) => setPlanChecklist({ ...planChecklist, [item.key]: e.target.checked })} /><span>{item.label}</span></label>)}<label><span>코멘트</span><textarea rows={6} value={planComment} onChange={(e) => setPlanComment(e.target.value)} placeholder="구체적인 검토 의견을 남겨 주세요." /></label><label><span>검토 결과</span><select value={planStatus} onChange={(e) => setPlanStatus(e.target.value)}><option value="revision">보완 필요</option><option value="approved">승인</option></select></label><button className="primary-button full" onClick={() => void postJson({ action: "reviewPlan", targetEmail: selectedEmail, reviewerComment: planComment, checklist: planChecklist, status: planStatus }, "기획안 검토 결과를 전달했습니다.")}>검토 결과 저장</button></aside></div> : <div className="admin-empty">기획안이 없습니다.</div>}</section>
        <section className="admin-detail-section"><div className="admin-section-heading"><span>03 · OPERATIONS</span><h2>강의 일정</h2></div><div className="admin-run-list">{selectedRuns.map((r) => <article key={r.id}><strong>{r.course_title}</strong><span>무료강의 {r.free_lecture_date}</span><span>커리큘럼 {r.curriculum_date}</span></article>)}{!selectedRuns.length && <div className="admin-empty">등록된 강의 일정이 없습니다.</div>}</div></section>
        <section className="admin-detail-section"><div className="admin-section-heading"><span>04 · CRISIS</span><h2>위기 이슈와 조치</h2></div><div className="admin-case-list">{selectedIssues.map((issue) => { const draft = issueDrafts[issue.id] ?? { action: issue.admin_action ?? "", reply: issue.admin_reply ?? "" }; return <article key={issue.id}><header><span className={`case-level level-${issue.severity}`}>{issue.severity}단계</span><strong>{issue.course_name} · {issue.category}</strong><time>{formatDate(issue.created_at)}</time></header><p>{issue.detail}</p><small>강사 즉시 조치: {issue.immediate_action || "없음"}</small><label><span>관리자 조치</span><textarea rows={2} value={draft.action} onChange={(e) => setIssueDrafts({ ...issueDrafts, [issue.id]: { ...draft, action: e.target.value } })} /></label><label><span>강사에게 보낼 답변</span><textarea rows={2} value={draft.reply} onChange={(e) => setIssueDrafts({ ...issueDrafts, [issue.id]: { ...draft, reply: e.target.value } })} /></label><div><button className="secondary-button" onClick={() => void postJson({ action: "reviewIssue", id: issue.id, status: "reviewing", adminAction: draft.action, adminReply: draft.reply }, "검토 중 조치를 저장했습니다.")}>검토 중 저장</button><button className="primary-button" onClick={() => void postJson({ action: "reviewIssue", id: issue.id, status: "resolved", adminAction: draft.action, adminReply: draft.reply }, "조치 완료로 저장했습니다.")}>조치 완료</button></div></article>; })}{!selectedIssues.length && <div className="admin-empty">접수된 위기 이슈가 없습니다.</div>}</div></section>
        <section className="admin-detail-section"><div className="admin-section-heading"><span>05 · SUPPORT</span><h2>문의와 답변</h2></div><div className="admin-support-list">{selectedSupports.map((item) => <article key={item.id}><header><span>{item.request_type}</span><time>{formatDate(item.created_at)}</time></header><p>{item.message}</p>{item.admin_reply ? <div className="saved-reply"><strong>답변 완료</strong><p>{item.admin_reply}</p></div> : <div className="admin-reply-box"><textarea value={replyDrafts[item.id] ?? ""} onChange={(e) => setReplyDrafts({ ...replyDrafts, [item.id]: e.target.value })} placeholder="문의 답변을 입력하세요." /><button className="primary-button" onClick={() => void postJson({ action: "replySupport", id: item.id, reply: replyDrafts[item.id] }, "문의 답변을 전달했습니다.")}>답변 보내기</button></div>}</article>)}{!selectedSupports.length && <div className="admin-empty">접수된 문의가 없습니다.</div>}</div></section>
      </> : <div className="admin-empty large">관리할 강사를 선택해 주세요.</div>}</div>}
    </main></section>{error && data && <div className="admin-toast error">{error}<button onClick={() => setError("")}>×</button></div>}{message && <div className="admin-toast">✓ {message}</div>}</div>;
}
